### PR TITLE
fix TH generation for normal ctrs

### LINKED ISSUE #2: Un-TH-able gadt?
```haskell
data A a where
  A :: A a
  B :: A (Just s)

makeFreer ''A
```

both of these appear to break the template haskell generation

### PR DESCRIPTION
**Pull request by isovector**
This PR adds support to the TH generation to allow non-GADT constructors to be automatically lifted to `Eff`. It's implemented by rewriting normal constructors as GADT constructors.

Fixes #2

### CODE REVIEW

File: src/Eff/TH.hs [hunk 1]
```diff
@@ -81,6 +81,7 @@ getDeclName = mkName . overFirst toLower . nameBase
 -- | Builds a function definition of the form @x a b c = send $ X a b c@.
 genDecl :: Con -> Q Dec
 genDecl (ForallC _ _ con) = genDecl con
+genDecl (NormalC cName tArgs') = genDecl $ GadtC [cName] tArgs' undefined
```
Comment (isovector) [inline src/Eff/TH.hs:84]: It's okay that this is `undefined` since that parameter is never inspected (line 85).

Comment (inanna-malick) [reply src/Eff/TH.hs:84]: can you add this as an inline comment?

**Review by inanna-malick — APPROVED** [review]
LGTM

**Review by shlevy — APPROVED** [review]
